<?php

namespace common\models;
use yii\db\ActiveRecord;
use frontend\models\Roles;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property int $role_id
 * @property string $username
 * @property string $password
 *
 * @property Adresses[] $adresses
 * @property Roles $role
 */

class User1 extends ActiveRecord implements \yii\web\IdentityInterface
{

    public $role_id;

    public static function tableName()
    {
        return 'users'; // TODO: Change the autogenerated stub
    }


    public function rules()
    {
        return [
            [['role_id', 'username', 'password'], 'required'],
            [['role_id'], 'integer'],
            [['username', 'password'], 'string'],
            [['role_id'], 'exist', 'skipOnError' => true, 'targetClass' => Roles::className(), 'targetAttribute' => ['role_id' => 'id']],
        ];
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        //return static::findOne(['access_token' => $token]);
    }


    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }


    public function getId()
    {
        return $this->id;
    }


    public function getAuthKey()
    {
        return null;
    }


    public function validateAuthKey($authKey)
    {
        return null;
    }


    public function validatePassword($password)
    {
        if ($password == $this->password){
            return true;
        } else {
            return false;
        }
    }


    public function getRole()
    {
        return $this->hasOne(Roles::className(), ['id' => 'role_id']);
    }


}